# Generated by Django 3.1.13 on 2022-08-14 01:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('fy_premium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fy_allowable', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('year', models.CharField(default='2022', max_length=4)),
                ('paid_in', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fund', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.fund')),
                ('subscriber', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_support', models.URLField()),
                ('status', models.CharField(blank=True, choices=[('A', 'Approved'), ('P', 'Pending'), ('I', 'Need Info'), ('D', 'Denied')], max_length=1, null=True)),
                ('subscriber_notes', models.CharField(blank=True, max_length=400, null=True)),
                ('system_notes', models.CharField(blank=True, max_length=400, null=True)),
                ('enrollment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.enrollment')),
                ('subscriber', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.subscriber')),
            ],
        ),
    ]
