# Generated by Django 3.1.13 on 2022-08-14 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220814_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='year',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='date_paid_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='year',
            field=models.CharField(default='2022', max_length=4),
        ),
    ]
