# Generated by Django 3.1.13 on 2022-08-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220814_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='uuid',
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='pub_key',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
