# Generated by Django 3.1.13 on 2022-08-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220814_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('I', 'Need Info'), ('D', 'Denied')], default='P', max_length=1),
        ),
    ]
