# Generated by Django 3.1.13 on 2022-08-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220814_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
