# Generated by Django 3.1.13 on 2022-08-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220814_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='subscriber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.subscriber'),
        ),
    ]
