# Generated by Django 3.1.13 on 2022-08-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220814_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='enrollment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='app.enrollment'),
        ),
    ]
