# Generated by Django 3.1.13 on 2022-08-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220814_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='chain_id',
            field=models.CharField(default=1111, max_length=40),
            preserve_default=False,
        ),
    ]
